/**
 * Core model-assignment logic for `neuralgentics --remodel`.
 *
 * The picker reads benchmark rankings from `presets.json` (generated by a
 * separate Python pipeline) and a `NeuralgenticsConfig` (providers +
 * overrides), then produces one `AgentAssignment` per agent role.
 *
 * Algorithm (per role):
 *   1. If `config.overrides[role]` has a `model` field, use it verbatim
 *      (overridden = true).
 *   2. Otherwise, scan every ENABLED provider's rankings for this role and
 *      pick the entry with the highest `score`. Ties broken by `rank` (lower
 *      wins), then by provider name (stable, alphabetical).
 *   3. If no enabled provider has a ranking for the role, fall back to the
 *      ollama default shipped in `FALLBACK_PRESETS`.
 *   4. If even the ollama fallback lacks the role, fall back to a generic
 *      `ollama/gpt-oss-20b` (the package's small_model).
 *
 * The picker is pure (no I/O, no network) — it takes already-loaded `presets`
 * + `config` and returns assignments. Network `GET /v1/models` filtering is
 * a separate concern handled by the caller (remodel.ts) before/after calling
 * `pickModels`, so the picker stays trivially testable.
 */

import type { NeuralgenticsConfig, AgentOverride } from "./config.js";

/** A single benchmark ranking entry for a (provider, role) pair. */
export interface RankingEntry {
  /** Model name WITHOUT the provider prefix (e.g. "kimi-k2.6"). */
  model: string;
  /** Benchmark-normalized score (0.0–1.0); higher is better. */
  score: number;
  /** Name of the benchmark (e.g. "swe_bench", "bfcl"). */
  benchmark: string;
  /** Rank within that benchmark (1 = best). */
  rank: number;
}

/** The shape of `presets.json`. */
export interface PresetsData {
  rankings: Record<string, Record<string, RankingEntry>>;
  agent_benchmark_map?: Record<
    string,
    {
      primary: string;
      secondary?: string;
      primary_weight: number;
      secondary_weight?: number;
    }
  >;
}

/** One agent's resolved model assignment. */
export interface AgentAssignment {
  role: string;
  /** Full "provider/model" id (e.g. "ollama/kimi-k2.6"). */
  model: string;
  /** Provider id that won (e.g. "ollama"). */
  provider: string;
  /** Benchmark the winning entry was scored on (empty for overrides). */
  benchmark: string;
  /** Score of the winning entry (0.0 for overrides / fallbacks). */
  score: number;
  /** True if the assignment came from `config.overrides` (not rankings). */
  overridden: boolean;
}

/** The 12 agent roles that need model assignments. */
export const AGENT_ROLES = [
  "orchestrator",
  "architect",
  "coder",
  "explorer",
  "tester",
  "reviewer",
  "linter",
  "git",
  "writer",
  "researcher",
  "release",
  "agent-builder",
] as const;

/**
 * Hardcoded fallback rankings used when `presets.json` is missing or lacks a
 * provider. Matches the current agent assignments shipped in the package so
 * `--remodel` with only ollama enabled is a no-op.
 */
export const FALLBACK_PRESETS: PresetsData = {
  rankings: {
    ollama: {
      orchestrator: { model: "kimi-k2.6", score: 0.85, benchmark: "bfcl", rank: 1 },
      architect: { model: "deepseek-v4-pro", score: 0.72, benchmark: "swe_bench", rank: 1 },
      coder: { model: "glm-5.2", score: 0.7, benchmark: "swe_bench", rank: 2 },
      explorer: { model: "deepseek-v4-flash", score: 0.75, benchmark: "chatbot_arena", rank: 3 },
      tester: { model: "deepseek-v4-flash", score: 0.7, benchmark: "swe_bench", rank: 3 },
      reviewer: { model: "deepseek-v4-pro", score: 0.72, benchmark: "mmlu_pro", rank: 2 },
      linter: { model: "qwen3.5:397b", score: 0.7, benchmark: "chatbot_arena", rank: 5 },
      git: { model: "minimax-m3", score: 0.68, benchmark: "chatbot_arena", rank: 6 },
      writer: { model: "mistral-large-3:675b", score: 0.78, benchmark: "chatbot_arena", rank: 4 },
      researcher: { model: "qwen3.5:397b", score: 0.7, benchmark: "mmlu_pro", rank: 5 },
      release: { model: "minimax-m3", score: 0.68, benchmark: "chatbot_arena", rank: 6 },
      "agent-builder": { model: "glm-5.2", score: 0.7, benchmark: "swe_bench", rank: 2 },
    },
  },
};

/** Generic fallback model when even ollama lacks a ranking for a role. */
const GENERIC_FALLBACK_MODEL = "ollama/gpt-oss-20b";

/** Return the list of enabled provider ids, in stable (insertion) order. */
export function enabledProviders(config: NeuralgenticsConfig): string[] {
  return Object.entries(config.providers)
    .filter(([, p]) => p.enabled)
    .map(([name]) => name);
}

/** Format a (provider, model) pair into the "provider/model" id string. */
function formatModelId(provider: string, model: string): string {
  if (model.includes("/")) {
    // Already prefixed — return as-is.
    return model;
  }
  return `${provider}/${model}`;
}

/** Compare two ranking entries: higher score first, then lower rank, then name. */
function compareRankings(a: RankingEntry, b: RankingEntry): number {
  if (a.score !== b.score) return b.score - a.score;
  if (a.rank !== b.rank) return a.rank - b.rank;
  return a.model.localeCompare(b.model);
}

/**
 * Pick the best model for a single role across all enabled providers.
 *
 * Returns `{ entry, provider }` or `null` if no enabled provider has a
 * ranking for the role.
 */
function pickFromRankings(
  role: string,
  config: NeuralgenticsConfig,
  presets: PresetsData,
): { entry: RankingEntry; provider: string } | null {
  let best: RankingEntry | null = null;
  let bestProvider = "";
  for (const provider of enabledProviders(config)) {
    const ranking = presets.rankings[provider]?.[role];
    if (ranking === undefined) continue;
    if (best === null || compareRankings(ranking, best) < 0) {
      best = ranking;
      bestProvider = provider;
    }
  }
  if (best === null) return null;
  return { entry: best, provider: bestProvider };
}

/** Resolve an override into a full assignment. */
function assignmentFromOverride(role: string, override: AgentOverride): AgentAssignment {
  const model = override.model ?? `${override.provider ?? "ollama"}/unknown`;
  // Best-effort provider extraction for overrides without an explicit provider.
  const provider = override.provider ?? model.split("/")[0] ?? "ollama";
  return {
    role,
    model,
    provider,
    benchmark: "",
    score: 0,
    overridden: true,
  };
}

/**
 * Produce one `AgentAssignment` per agent role.
 *
 * The `dryRun` parameter is accepted for API symmetry but does not change the
 * result — the picker is pure and never writes. The caller (`remodel.ts`)
 * decides whether to apply the assignments.
 */
export function pickModels(
  config: NeuralgenticsConfig,
  presets: PresetsData,
  _dryRun: boolean,
): AgentAssignment[] {
  const assignments: AgentAssignment[] = [];
  for (const role of AGENT_ROLES) {
    const override = config.overrides[role];
    if (override !== undefined) {
      assignments.push(assignmentFromOverride(role, override));
      continue;
    }
    const fromRankings = pickFromRankings(role, config, presets);
    if (fromRankings !== null) {
      const { entry, provider } = fromRankings;
      assignments.push({
        role,
        model: formatModelId(provider, entry.model),
        provider,
        benchmark: entry.benchmark,
        score: entry.score,
        overridden: false,
      });
      continue;
    }
    // No ranking from any enabled provider — fall back to ollama defaults.
    const fallback = FALLBACK_PRESETS.rankings.ollama?.[role];
    if (fallback !== undefined) {
      assignments.push({
        role,
        model: formatModelId("ollama", fallback.model),
        provider: "ollama",
        benchmark: fallback.benchmark,
        score: fallback.score,
        overridden: false,
      });
      continue;
    }
    // Absolute last resort.
    assignments.push({
      role,
      model: GENERIC_FALLBACK_MODEL,
      provider: "ollama",
      benchmark: "",
      score: 0,
      overridden: false,
    });
  }
  return assignments;
}