// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/embedding/v1/embedding.proto

package embeddingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // optional model override, empty = default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_v1_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dimensions    int32                  `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyUs     int64                  `protobuf:"varint,4,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"` // microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_v1_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *EmbedResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedResponse) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_embedding_v1_embedding_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ready" or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_embedding_v1_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_embedding_v1_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_embedding_v1_embedding_proto protoreflect.FileDescriptor

const file_proto_embedding_v1_embedding_proto_rawDesc = "" +
	"\n" +
	"\"proto/embedding/v1/embedding.proto\x12\fembedding.v1\"8\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"|\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\x05R\n" +
	"dimensions\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x04 \x01(\x03R\tlatencyUs\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe4\x01\n" +
	"\x10EmbeddingService\x12@\n" +
	"\x05Embed\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponse\x12I\n" +
	"\n" +
	"EmbedBatch\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponse(\x010\x01\x12C\n" +
	"\x06Health\x12\x1b.embedding.v1.HealthRequest\x1a\x1c.embedding.v1.HealthResponseB.Z,neuralgentics/proto/embedding/v1;embeddingpbb\x06proto3"

var (
	file_proto_embedding_v1_embedding_proto_rawDescOnce sync.Once
	file_proto_embedding_v1_embedding_proto_rawDescData []byte
)

func file_proto_embedding_v1_embedding_proto_rawDescGZIP() []byte {
	file_proto_embedding_v1_embedding_proto_rawDescOnce.Do(func() {
		file_proto_embedding_v1_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_embedding_v1_embedding_proto_rawDesc), len(file_proto_embedding_v1_embedding_proto_rawDesc)))
	})
	return file_proto_embedding_v1_embedding_proto_rawDescData
}

var file_proto_embedding_v1_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_embedding_v1_embedding_proto_goTypes = []any{
	(*EmbedRequest)(nil),   // 0: embedding.v1.EmbedRequest
	(*EmbedResponse)(nil),  // 1: embedding.v1.EmbedResponse
	(*HealthRequest)(nil),  // 2: embedding.v1.HealthRequest
	(*HealthResponse)(nil), // 3: embedding.v1.HealthResponse
}
var file_proto_embedding_v1_embedding_proto_depIdxs = []int32{
	0, // 0: embedding.v1.EmbeddingService.Embed:input_type -> embedding.v1.EmbedRequest
	0, // 1: embedding.v1.EmbeddingService.EmbedBatch:input_type -> embedding.v1.EmbedRequest
	2, // 2: embedding.v1.EmbeddingService.Health:input_type -> embedding.v1.HealthRequest
	1, // 3: embedding.v1.EmbeddingService.Embed:output_type -> embedding.v1.EmbedResponse
	1, // 4: embedding.v1.EmbeddingService.EmbedBatch:output_type -> embedding.v1.EmbedResponse
	3, // 5: embedding.v1.EmbeddingService.Health:output_type -> embedding.v1.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_embedding_v1_embedding_proto_init() }
func file_proto_embedding_v1_embedding_proto_init() {
	if File_proto_embedding_v1_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_embedding_v1_embedding_proto_rawDesc), len(file_proto_embedding_v1_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_embedding_v1_embedding_proto_goTypes,
		DependencyIndexes: file_proto_embedding_v1_embedding_proto_depIdxs,
		MessageInfos:      file_proto_embedding_v1_embedding_proto_msgTypes,
	}.Build()
	File_proto_embedding_v1_embedding_proto = out.File
	file_proto_embedding_v1_embedding_proto_goTypes = nil
	file_proto_embedding_v1_embedding_proto_depIdxs = nil
}
