# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from embedding.v1 import embedding_pb2 as embedding_dot_v1_dot_embedding__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding/v1/embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """EmbeddingService provides text-to-vector embedding via gRPC.
    The Python sidecar implements this service; the Go memory module
    connects as a client.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/embedding.v1.EmbeddingService/Embed',
                request_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.stream_stream(
                '/embedding.v1.EmbeddingService/EmbedBatch',
                request_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/embedding.v1.EmbeddingService/Health',
                request_serializer=embedding_dot_v1_dot_embedding__pb2.HealthRequest.SerializeToString,
                response_deserializer=embedding_dot_v1_dot_embedding__pb2.HealthResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """EmbeddingService provides text-to-vector embedding via gRPC.
    The Python sidecar implements this service; the Go memory module
    connects as a client.
    """

    def Embed(self, request, context):
        """Embed generates a single embedding vector from text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request_iterator, context):
        """EmbedBatch generates embeddings for multiple texts in a streaming fashion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health checks if the sidecar is ready to serve requests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.FromString,
                    response_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.FromString,
                    response_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=embedding_dot_v1_dot_embedding__pb2.HealthRequest.FromString,
                    response_serializer=embedding_dot_v1_dot_embedding__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.v1.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """EmbeddingService provides text-to-vector embedding via gRPC.
    The Python sidecar implements this service; the Go memory module
    connects as a client.
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/Embed',
            embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/embedding.v1.EmbeddingService/EmbedBatch',
            embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.v1.EmbeddingService/Health',
            embedding_dot_v1_dot_embedding__pb2.HealthRequest.SerializeToString,
            embedding_dot_v1_dot_embedding__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
