# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding/v1/embedding.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'embedding/v1/embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65mbedding/v1/embedding.proto\x12\x0c\x65mbedding.v1\"+\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"V\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x12\n\ndimensions\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t\x12\x12\n\nlatency_us\x18\x04 \x01(\x03\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe4\x01\n\x10\x45mbeddingService\x12@\n\x05\x45mbed\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponse\x12I\n\nEmbedBatch\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponse(\x01\x30\x01\x12\x43\n\x06Health\x12\x1b.embedding.v1.HealthRequest\x1a\x1c.embedding.v1.HealthResponseB.Z,neuralgentics/proto/embedding/v1;embeddingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding.v1.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,neuralgentics/proto/embedding/v1;embeddingpb'
  _globals['_EMBEDREQUEST']._serialized_start=46
  _globals['_EMBEDREQUEST']._serialized_end=89
  _globals['_EMBEDRESPONSE']._serialized_start=91
  _globals['_EMBEDRESPONSE']._serialized_end=177
  _globals['_HEALTHREQUEST']._serialized_start=179
  _globals['_HEALTHREQUEST']._serialized_end=194
  _globals['_HEALTHRESPONSE']._serialized_start=196
  _globals['_HEALTHRESPONSE']._serialized_end=228
  _globals['_EMBEDDINGSERVICE']._serialized_start=231
  _globals['_EMBEDDINGSERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
