/**
 * Neuralgentics — Self-Evolution Gate Skill and Agent Templates
 *
 * Template strings for generating SKILL.md files and AGENTS.md entries.
 * Based on the boomerang-agent-builder SKILL.md structure.
 *
 * Adapted from boomerang-v3 for the Neuralgentics namespace.
 * All "boomerang" references changed to "neuralgentics" or generic terms.
 */

/**
 * Generate a SKILL.md file from a pattern candidate.
 *
 * @param name - kebab-case skill name
 * @param description - One-line description
 * @param instructions - Role description lines
 * @param triggers - When to use this skill
 * @param workflow - Workflow steps
 * @param outputFormat - Expected output description
 */
export function generateSkillMarkdown(params: {
  name: string;
  description: string;
  instructions: string[];
  triggers: string[];
  workflow: string[];
  outputFormat: string;
}): string {
  const instructionLines = params.instructions
    .map((line, i) => `${i + 1}. ${line}`)
    .join('\n');
  const triggerLines = params.triggers
    .map((t) => `- ${t}`)
    .join('\n');
  const workflowLines = params.workflow
    .map((step, i) => `### Step ${i + 1}\n${step}`)
    .join('\n\n');
  const title = params.name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  return `---
name: ${params.name}
description: ${params.description}
---

# ${title}

## Description
${params.description}

## Instructions

You are the **${title}** specialist. Your role is:
${instructionLines}

## Triggers

Use this skill when:
${triggerLines}

## Model

Use **MiniMax M2.7** for fast, efficient execution.

## Workflow

${workflowLines}

## Output Format

${params.outputFormat}

## Memory Integration

- Query memory for relevant context before starting work
- Save results to memory after completion
- Use trust signals (agent_used, user_confirmed) for quality feedback

## Escalation

| Situation | Escalate To |
|-----------|-------------|
| Complex design decisions | neuralgentics-architect |
| Need user confirmation | Return to orchestrator |

---

*Auto-generated by Neuralgentics Self-Evolution Gate*
`;
}

/**
 * Generate an AGENTS.md entry for a new agent.
 *
 * @param name - Agent name (kebab-case)
 * @param skill - Associated skill name
 * @param model - Recommended model
 * @param description - Agent description
 * @param justification - Why this model/agent
 */
export function generateAgentEntry(params: {
  name: string;
  skill: string;
  model: string;
  description: string;
  justification: string;
}): string {
  return `| **${params.name}** | ${params.skill} | ${params.model} | ${params.justification} |`;
}

/**
 * Default skill template with placeholder content derived from a pattern candidate.
 */
export const SKILL_TEMPLATE = `---
name: {{name}}
description: {{description}}
---

# {{title}}

## Description
{{description}}

## Instructions

You are the **{{title}}** specialist. Your role is:
1. {{instruction1}}
2. {{instruction2}}

## Triggers

Use this skill when:
- {{trigger1}}
- {{trigger2}}

## Model

Use **MiniMax M2.7** for fast, efficient execution.

## Workflow

### Step 1
{{workflow1}}

### Step 2
{{workflow2}}

## Output Format

{{outputFormat}}

## Memory Integration

- Query memory for relevant context before starting work
- Save results to memory after completion
- Use trust signals (agent_used, user_confirmed) for quality feedback

## Escalation

| Situation | Escalate To |
|-----------|-------------|
| Complex design decisions | neuralgentics-architect |
| Need user confirmation | Return to orchestrator |

---

*Auto-generated by Neuralgentics Self-Evolution Gate*
`;

/**
 * Map a pattern description to reasonable skill parameters.
 * Extracts a name, description, triggers, and workflow from the pattern text.
 */
export function patternToSkillParams(pattern: string, suggestedName: string): {
  name: string;
  description: string;
  instructions: string[];
  triggers: string[];
  workflow: string[];
  outputFormat: string;
} {
  const title = suggestedName
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  // Extract action phrases from the pattern text
  const sentences = pattern
    .split(/[.!?]+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  const instructions =
    sentences.length >= 2
      ? [sentences[0], sentences[1]]
      : [`Execute the ${title} workflow`, `Report results to orchestrator`];

  const triggers = [
    `User requests ${suggestedName.replace(/-/g, ' ')} task`,
    `Pattern detected: ${pattern.slice(0, 60)}${pattern.length > 60 ? '...' : ''}`,
  ];

  const workflow =
    sentences.length >= 2
      ? [sentences[0], sentences.slice(2).join('. ') || 'Report results']
      : [`Execute ${title} workflow`, 'Report results to orchestrator'];

  return {
    name: suggestedName,
    description: `Auto-generated skill for: ${pattern.slice(0, 80)}${pattern.length > 80 ? '...' : ''}`,
    instructions,
    triggers,
    workflow,
    outputFormat: `Summary of ${title} execution with results and any follow-up actions.`,
  };
}